version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  forntend:
    build:
      context: ./forntend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
